export const adminSideBarLinks = [
  {
    img: '/icons/house-solid-or.svg',
    route: '/dashboard',
    text: 'Home',
  },
  {
    img: '/icons/user-solid-ic.svg',
    route: '/dashboard/employee',
    text: 'Employee',
  },
  {
    img: '/icons/cart-shopping-solid.svg',
    route: '/dashboard/purchasing',
    text: 'Purchasing',
  },
  {
    img: '/icons/coins-solid.svg',
    route: '/dashboard/finance',
    text: 'Finance',
  },
  {
    img: '/icons/warehouse-solid.svg',
    route: '/dashboard/warehouse',
    text: 'Warehouse',
  },
];

export const translations = {
  en: {
    login: 'Login',
    logout: 'Logout',
    dashboard: 'Dashboard',
    employee: 'Employee',
    purchasing: 'Purchasing',
    finance: 'Finance',
    warehouse: 'Warehouse',
    welcomeAdmin: 'Welcome, Admin',
    email: 'Email',
    password: 'Password',
    home: 'Home',
    page: 'Page',
    financePage: 'Finance Page',
    employeePage: 'Employee Page',
    dashboardPage: 'Dashboard Page',
    warehousePage: 'Warehouse Page',
    purchasingPage: 'Purchasing Page',
    language: 'Language',
  },
  id: {
    login: 'Masuk',
    logout: 'Keluar',
    dashboard: 'Dasbor',
    employee: 'Karyawan',
    purchasing: 'Pembelian',
    finance: 'Keuangan',
    warehouse: 'Gudang',
    welcomeAdmin: 'Selamat datang, Admin',
    email: 'Email',
    password: 'Kata Sandi',
    home: 'Beranda',
    page: 'Halaman',
    financePage: 'Halaman Keuangan',
    employeePage: 'Halaman Karyawan',
    dashboardPage: 'Halaman Dasbor',
    warehousePage: 'Halaman Gudang',
    purchasingPage: 'Halaman Pembelian',
    language: 'Bahasa',
  },
  zh: {
    login: '登录',
    logout: '登出',
    dashboard: '仪表板',
    employee: '员工',
    purchasing: '采购',
    finance: '财务',
    warehouse: '仓库',
    welcomeAdmin: '欢迎, 管理员',
    email: '电子邮件',
    password: '密码',
    home: '首页',
    page: '页面',
    financePage: '财务页面',
    employeePage: '员工页面',
    dashboardPage: '仪表板页面',
    warehousePage: '仓库页面',
    purchasingPage: '采购页面',
    language: '语言',
  },
};
